<a href="https://colab.research.google.com/github/liuxiao916/Dive_into_DL_PyTorch/blob/main/4_5_%E8%AF%BB%E5%8F%96%E5%92%8C%E5%AD%98%E5%82%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4.5 读取和存储

In [2]:
import torch
from torch import nn

### 4.5.1 读写Tensor

In [3]:
x = torch.ones(3)
torch.save(x, 'x.pt')

In [4]:
x2 = torch.load('x.pt')
x2

tensor([1., 1., 1.])

In [5]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')
xy_list = torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

In [6]:
torch.save({'x': x, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

### 4.5.2 读写模型

1. state_dict

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

net = MLP()
net.state_dict()


OrderedDict([('hidden.weight', tensor([[ 5.0908e-01,  4.3209e-04, -1.2920e-02],
                      [ 1.0964e-01,  4.0891e-01,  2.4522e-01]])),
             ('hidden.bias', tensor([-0.5677,  0.3438])),
             ('output.weight', tensor([[0.5114, 0.0503]])),
             ('output.bias', tensor([0.6290]))])

In [14]:
for name, param in net.named_parameters():
    print(name)
    print(param)

hidden.weight
Parameter containing:
tensor([[ 5.0908e-01,  4.3209e-04, -1.2920e-02],
        [ 1.0964e-01,  4.0891e-01,  2.4522e-01]], requires_grad=True)
hidden.bias
Parameter containing:
tensor([-0.5677,  0.3438], requires_grad=True)
output.weight
Parameter containing:
tensor([[0.5114, 0.0503]], requires_grad=True)
output.bias
Parameter containing:
tensor([0.6290], requires_grad=True)


In [15]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()

{'param_groups': [{'dampening': 0,
   'lr': 0.001,
   'momentum': 0.9,
   'nesterov': False,
   'params': [0, 1, 2, 3],
   'weight_decay': 0}],
 'state': {}}

2. 保存和加载模型

In [16]:
X = torch.randn(2, 3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])

In [18]:
torch.save(net.state_dict(), PATH) 

In [19]:
net2 = MLP()
net2.load_state_dict(torch.load(PATH))

<All keys matched successfully>

In [20]:
torch.save(net, PATH)

In [21]:
model = torch.load(PATH)