<a href="https://colab.research.google.com/github/liuxiao916/Dive_into_DL_PyTorch/blob/main/4_6_GPU%E8%AE%A1%E7%AE%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 4.6 GPU计算

In [1]:
import torch
from torch import nn

torch.cuda.is_available()

True

### 4.6.1 计算设备

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.current_device()

0

In [4]:
torch.cuda.get_device_name(0)

'Tesla P100-PCIE-16GB'

### 4.6.2 Tensor的GPU计算

In [6]:
x = torch.tensor([1, 2, 3])

In [9]:
x.device

device(type='cpu')

1. GPU上的存储

In [10]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [11]:
x.device

device(type='cuda', index=0)

In [12]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)

x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

2. GPU上的计算

In [13]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

### 4.6.3 模型的GPU计算

In [16]:
net = nn.Sequential(nn.Linear(3, 1))
list(net.parameters())[0].device

device(type='cpu')

In [18]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [19]:
x = torch.rand(2,3).cuda()
net(x)


tensor([[0.0937],
        [0.2483]], device='cuda:0', grad_fn=<AddmmBackward>)